### ISSUE TITLE
关于 listeners 配置项的疑问

### ISSUE THREAD

**Issue by GarrenZhang** [kinglisky/egrid#10]
你好作者, 我有一点关于 listeners 配置项的疑问,
listeners 可以用来监听自定义组件 emit 的事件
但是在 listeners 选项中 定义的函数 如何触发 egrid 组件所在作用域即 egrid 父组件中的函数呢
这里面的函数似乎是没有绑定 this 的
如果用箭头函数的话 假如配置项 columns 放在外部文件来引入 会指向引入的对象
求解惑

**Comment by kinglisky** [comment]
@GarrenZhang 
![](https://i.loli.net/2018/04/25/5adf5d41937cd.jpg)
可以看下：https://jsfiddle.net/nlush/upyryb8e/1/

**Comment by GarrenZhang** [comment]
作为第一次提issue的小白,收到作者这么快的回复表示很感谢.
是这样的 我完全理解你回复的代码示例,但是项目表格很多,并且每一列基本都有特殊的template结构,
我现在需要将columns的配置文件写在外面,作为单独的文件引入,你提供的columnsSchema是可以对一列单独处理,但是需要特殊处理的列多的情况下,是不是减少的代码量就没那么明显了.下面是我基于你的egird弄出来的解决办法...有点不够优雅, 但也算实现了我需要的columns配置 和 主文件分离的需求了...把内部组件的this emit出来 通过找祖先组件的方式找到了 根组件 ...  
`{
      label: '测试',
      width: '60',
      listeners: {
        detailClick (data) {
          const _this = data.$parent.$parent.$parent.$parent
          _this.handleDetailClick(data.row)
        }
      },
      component: {
        props: ['row'],
        render (h) {
          return (
            <div
              class='chover'
              style={ {
                textDecoration: 'underline',
                cursor: 'pointer',
                height: '20px',
                width: '30px'
              } }
              onClick={() => {this.$emit('detailClick', this)}}
            >
              详情
            </div>
          )
        }
      }
    }
`

**Comment by kinglisky** [comment]
```javascript
listeners: {
    detailClick(data) {
      const _this = data.$parent.$parent.$parent.$parent
      _this.handleDetailClick(data.row)
    }
}
```

不推荐这样处理，以后父级组件有稍稍变动就 GG 了，这种直接使用 `Event Bus` 或者是 `Vuex` 来处理了，耦合性没那么强。


然后关于：

> columnsSchema 是可以对一列单独处理,但是需要特殊处理的列多的情况下,是不是减少的代码量就没那么明显了

其实如果每一列的渲染组件都不一样的话，肯定是跑不了为每一列单独配置的，但是还是有些解决方法的：

使用 `columnsProps` ,  `columnsProps` 可以为所有的列设置一些公共的属性，例如 `width` `min-width` 一类的，当然也包括组件。

```
const columnsProps = {
  width: 100,
  component: CommonCpt,
  listeners： {
    ......
  }
}
```
 `CommonCpt` 是所有列通用的组件，你可以为所有列写一个通用组件，每列的渲染由 `CommonCpt` 处理。

`CommonCpt`  的内部大概是：

```html
<template>
  <component v-bind="$props" :is="currCpt"></component>
</template>

<script>
// 具体的列组件的逻辑具体实现
import Btn from 'cpt/btn'
import Editor from 'cpt/editor'
import Text from 'cpt/text'


// 使用列名 `col.label` 或 `col.prop` 做映射
const CPT_MAP = {
  '操作': Btn,
  '编辑': Editor,
  '详情': Text,
  '地址': Text,
  ......
}

export default {
  props: ['row', 'col'],

  computed: {
    currCpt () {
      return CPT_MAP[this.col.label]
    }
  }
}
</script>
```
但不太推荐。

平时列不多而且表格 `columns` 是由自己生成的话，完全可以通过 `columns` 来配置。

```javascript
const columns = [
  {
    label: '地址',
    prop: 'adds'
  },
   {
    label: '邮编',
    prop: 'zip',
    width: 100,
    componet: someCpt,
    listeners: {}
  },
  ......
]
```

比较推荐这种方式。

`columnsSchema` 是为了处理一些特殊列的渲染，例如 `columnsProps` 配置了所有列的组件，然后想为某一列单独处理就可以用 `columnsSchema`  来处理。

还有就是和后端铜须约定好表格数据接口格式后，后端返回的数据就直接包含了 `columns` 个 `rows`:

```javascript
const data = {
   columns: [{ label: 'xxx', prop: 'xxx' }, ....]
   rows: [{...}, {...}]
}
```

@GarrenZhang 

这种就直接使用 `columnsSchema` 来处理会更方便点。

这边用的比较多的**高阶组件**的封装方法，`v-bind` `v-on` `$attrs` `$props` `listeners` .... 还是挺好用的可以好好研究一下，`vue` 的官方文档上都有写。

P.S 以后提 ` issue` 格式啥的可以调调~ over

![](https://i.loli.net/2018/04/25/5adff1926b762.jpg)

**Comment by GarrenZhang** [comment]
灰常感谢

**Comment by GarrenZhang** [comment]
非常详细, 再次感谢作者大大
