### ISSUE TITLE
为何没有整合分页

### ISSUE THREAD

**Issue by xuningfans** [kinglisky/egrid#11]
感觉有表格必有分页，可以不可以考虑整合一下pagination？

**Comment by kinglisky** [comment]
@xuningfans 
![](https://i.loli.net/2018/05/07/5aefab127c5d0.jpg)

其实也有很多任务场景下，不带分页的表格也是很常见的。

分页的逻辑是用来控制外层的 `data` 的，这部分的逻辑可以自己实现，没必要加到表格组件内部，表格只提供核心的表格数据的展示。需要在表格控件的基础上在封装一层分页（一般会带有数据请求）逻辑作为一个高阶组件。

**Comment by xuningfans** [comment]
用了一天，发现扩展性没了，API也不友好，换这个了https://www.jianshu.com/p/26604e6a117a
