### ISSUE TITLE
多级表头数据怎么定义

### ISSUE THREAD

**Issue by liub1934** [kinglisky/egrid#12]
多级表头数据怎么定义，貌似没看到有处理多级表头

**Comment by kinglisky** [comment]
![](https://i.loli.net/2018/06/26/5b3196b031bd2.jpg)
@liub1934 昨天小试了一下，多级表头暂时没有好的方法直接使用，我琢磨琢磨。

**Comment by liub1934** [comment]
弄了个简单的多级表头的，可以无限嵌套：https://jsfiddle.net/mmx38qxw/3245
但是自定义列模板的solt用不了了= =，
![image](https://user-images.githubusercontent.com/29849550/42263807-aa91573e-7fa1-11e8-8ab4-f1662fd46e57.png)，这里的solt起不了作用了，理想中的是可以用solt做自定义显示的
![image](https://user-images.githubusercontent.com/29849550/42264027-20cdf43e-7fa2-11e8-8541-d882675493b5.png)

**Comment by hanzhenchaoGit** [comment]
<template>
    <el-table-column v-if="column.type" :type="column.type">
    </el-table-column>
    <el-table-column v-else
    :prop="column.prop"
    :column-key="column.columnKey"
    :label="column.label"
    :fixed="column.fixed"
    :width="column.width"
    :render-header="column.renderHeader"
    :sortable="column.sortable"
    :sort-method="column.method"
    :resizable="column.resizable"
    :formatter="column.formatter"
    :show-overflow-tooltip="column.showOverflowTooltip"
    :align="column.align"
    :header-align="column.headerAlign || column.align"
    :class-name="column.className"
    :label-class-name="column.labelClassName"
    :selectable="column.selectable"
    :reserve-selection="column.reserveSelection"
    :filters="column.filters"
    :filter-placement="column.filterPlacement"
    :filter-multiple="column.filterMultiple"
    :filter-method="column.filterMethod"
    :filtered-value="column.filteredValue"
    >
  <template v-if="column.children">
    <c-column v-for="(item, index) in column.children"
      :key="index"
      :column="item"></c-column>
  </template>
  <template v-slot:default="slotProps">
    <span v-if="column.filter">
      {{ Vue.filter(column['filter'])(slotProps.row[column.prop]) }}
    </span>
    <span v-else-if="column.slotName">
      <slot :name="column.slotName" :row="slotProps.row" :$index="slotProps.$index" />
    </span>
    <span v-else>
      {{ column.render ? column.render(slotProps.row) : slotProps.row[column.prop] }}
    </span>
  </template>
  </el-table-column>
</template>

**Comment by hanzhenchaoGit** [comment]
![image](https://user-images.githubusercontent.com/20226394/54411097-126ee700-4729-11e9-9989-103a11a60f0a.png)

**Comment by liub1934** [comment]
已经搞定，自己重新二次封装下，几乎支持element的所有事件是属性https://github.com/liub1934/lb-element-table
