### ISSUE TITLE
你好，我在项目中引用时，在表格所在路由刷新页面后的展示没有问题。但是如果从路由其他路由页面跳转路由，进入表格所在组件，会出现表格的横向滚动条失效的问题。

### ISSUE THREAD

**Issue by li447419358** [kinglisky/egrid#13]
`<egrid
    :data="data"
    :columns="columns"
    :table-name="TABLE_NAME"
    :column-type="['selection']"
    :columns-props="columnsProps"
    :columns-schema="columnsSchema"
    @sort-change="sortChange"
    @selection-change="selectionChange"
    highlight-current-row
    border></egrid>`

**Comment by kinglisky** [comment]
@li447419358 能给个重现的 `demo` 吗？`jsfiddle` 或者是 `codepen` 的，这样会方便点。

**Comment by li447419358** [comment]
@kinglisky   我好像解决了。我项目里面是动态给的columns，并且让用户自定义栏位，直接从vuex里面获取；所以会在main.vue里面去获取用户的已保存的习惯。并将这个放到vuex里面；

之前写的比较麻烦，vuex会直接先获取了localStorage初始化，然后又从js文件中获取了配置初始化到vuex。然后又去获取了后台的用户习惯并与js中的配置合并后初始化到vuex；

我现在去掉了从localStorage获取配置与从基本配置获取初始化vuex这两步步。vuex默认直接读基本配置，用户习惯获取到了就合并下再去改变下vuex。好像就没问题了。。

**Comment by kinglisky** [comment]
![](https://i.loli.net/2018/09/07/5b9237d02876d.jpg)

**Comment by li447419358** [comment]
@kinglisky 
![](https://i.loli.net/2018/09/07/5b923962874c4.jpg)

**Comment by li447419358** [comment]
![](https://i.loli.net/2018/09/07/5b923962874c4.jpg)

**Comment by li447419358** [comment]
@kinglisky 
![](https://i.loli.net/2018/09/07/5b923962874c4.jpg)
