### ISSUE TITLE
您好，有个问题想请教下你  我想在你的e-grid组件中使用自定义组件 并且绑定值应该怎么做呢？

### ISSUE THREAD

**Issue by xiaoxigua-web** [kinglisky/egrid#14]
<el-table-column label="居住区域" min-width="120" fixed="left">
            <template slot-scope="scope">
              <el-zone-area :zone="zoneFormatter(scope.row)"  :get-item="getZone"></el-zone-area>
            </template>
          </el-table-column>

**Comment by kinglisky** [comment]
https://jsfiddle.net/nlush/48dponcu/1/

http://kinglisky.github.io/egrid

文档有基本的演示，jsfiddle 最近访问比较慢。

@gu12
