### ISSUE TITLE
如何针对cell使用element-ui的el-tooltip标签

### ISSUE THREAD

**Issue by zhongnan1996** [kinglisky/egrid#2]

**Comment by kinglisky** [comment]
@zhongnan1996

https://jsfiddle.net/nlush/hL0j6rnn/

可以通过 `columnsSchema` 为你需要 tool-tip 的列设置 `showOverflowTooltip: true` 属性就行了。

```javascript
columnsSchema: {
  '地址': {
    showOverflowTooltip: true
  }
}
```

**Comment by YooLin** [comment]
如何给table设置Index序号，试了type: 'index'好像没效果

**Comment by wyyyy** [comment]
https://jsfiddle.net/nlush/hL0j6rnn/ 这是什么网站 ，经常性的打不开
