### ISSUE TITLE
操作那一列能否设置多个自定义功能的按钮吗

### ISSUE THREAD

**Issue by YooLin** [kinglisky/egrid#3]
如题，求解答~ 目前没有找到添加方式

**Comment by kinglisky** [comment]
@YooLin 
额，这就是个举一反三的问题，操作的那一列的组件是你自己定义的组件，那使用时可以根据需要定义自己的按钮。

https://jsfiddle.net/nlush/48dponcu/1/

**Comment by YooLin** [comment]
嘿嘿，原谅一下小白~ 麻烦看下这种情况没有渲染出来
http://jsfiddle.net/yr0uf0fm/18/

**Comment by YooLin** [comment]
谢谢大佬，我再去试试~
