### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by YooLin** [kinglisky/egrid#4]
1.columnType属性能否自定义label属性呢？就是把那个"#"改成自定义的文字描述，如：序号/新增等呢？
2.是否支持指定列设置为下拉选呢？
3.是否可以指定列添加校验规则呢？如，电话/邮箱设置校验电话/邮箱的校验规则呢？
http://jsfiddle.net/yr0uf0fm/23/

**Comment by kinglisky** [comment]
每一列的对应的组件是你自己定义的组件，如果要实现下拉和字段校验只需要配置每列对应的自定义组件就行：

```javascript
columnsSchema: {
  '邮箱': {
    component: EmailEditor // 这里配置自定义的组件
  }
}
```
