### ISSUE TITLE
关于折叠表格的

### ISSUE THREAD

**Issue by wyyyy** [kinglisky/egrid#8]
1.折叠表格一般都是列比较的多，打开折叠的会把基本的列展现出来，折叠里面的是别的列，现在我看demo里面折叠和直观看的列是一样的，这一个能设置嘛

**Comment by kinglisky** [comment]
@wyyyy 可以的， `cloumns` 可控制你想渲染列，而 `expand` 展开的内容是你自己定义的。

可以参考 https://jsfiddle.net/nlush/o0qq716t/

**Comment by wyyyy** [comment]
你好，这一个项目还会更新嘛？我想问一下，想要别的功能 ，就是单元格的编辑功能，可以考虑加上嘛？

**Comment by kinglisky** [comment]
![](https://i.loli.net/2018/04/18/5ad73345e11ed.jpg)
@wyyyy 单元格编辑功能是由你自定义的列组件控制，文档的 demo 中已经实现了，可以看一下。

**Comment by wyyyy** [comment]
你好，你建qq群嘛？有很多问题想问一下。谢谢
